### ISSUE TITLE
Errors during make process

### ISSUE THREAD

**Issue by gmslater** [portaloffreedom/pipecontrol#9]
Installing PipeControl on Ubuntu Studio 23.04.
Running **cmake** is successful. After that, running either **make** or **make install** generates the following errors (screenshot attached):

![pipecontrol_make_errors](https://github.com/portaloffreedom/pipecontrol/assets/65368204/5b8fca06-6f5c-480f-a1c3-b385d334fe17)

**Comment by portaloffreedom** [comment]
The issue comes from outdated pipewire headers. Ubuntu does not provide up to date packages. The solution is to use pipecontrol 0.2.8 https://github.com/portaloffreedom/pipecontrol/releases/tag/v0.2.8 until ubuntu has a new release with up to date packages.
